/** @file hv.h
 *
 *  @brief The export point for hypervisor module
 *
 *  For those outside hypervisor module, just include hv.h is enough
 *
 *  @author Leiyu Zhao
 */

#ifndef HV_H
#define HV_H

#include "hvseg.h"
#include "hvlife.h"
#include "hv_hpcall.h"

// init all hypervisor related things.
// Call it in kernel initialization
void initHypervisor();

// This forward timer interrupt to active hypervisor. Kernel should call it
// asynchonously in timer callback
void hv_CallMeOnTick(HyperInfo* info);

// A fault.c-compatible fault handler.
// When the fault is generated by hypervisor, pass it to this.
// This handler never returns
bool HyperFaultHandler(int es, int ds, int edi, int esi, int ebp,
    int ebx, int edx, int ecx, int eax, int faultNumber, int errCode,
    int eip, int cs, int eflags, int esp, int ss, int cr2);

#endif
